# Generated by Django 2.2 on 2020-02-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_box_office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='rent_start',
            field=models.DateField(null=True),
        ),
    ]
