# Generated by Django 2.2 on 2020-02-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_box_office', '0002_session_rent_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='rent_start',
        ),
    ]
