# Generated by Django 2.2 on 2020-02-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_box_office', '0003_remove_session_rent_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
