# Generated by Django 2.2 on 2020-02-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_box_office', '0004_auto_20200213_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
