# Generated by Django 2.2 on 2020-02-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_box_office', '0005_ticket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
