# Generated by Django 2.2 on 2020-02-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_box_office', '0006_auto_20200214_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_box_office.Movie'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
