# Generated by Django 2.2 on 2020-02-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_box_office', '0007_auto_20200214_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_at']},
        ),
    ]
