# Generated by Django 2.2 on 2020-02-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_box_office', '0008_auto_20200215_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
